##################################################
# file: termine_types.py
#
# schema types generated by "ZSI.generate.wsdl2python.WriteServiceModule"
#    /usr/bin/wsdl2py http://www.nactem.ac.uk/software/termine/webservice/termine.wsdl
#
##################################################

import ZSI
import ZSI.TCcompound
from ZSI.schema import LocalElementDeclaration, ElementDeclaration, TypeDefinition, GTD, GED

##############################
# targetNamespace
# urn:termine
##############################

class ns0:
    targetNamespace = "urn:termine"

# end class ns0 (tns: urn:termine)
